FROM ocaml/opam:alpine_ocaml-4.04.2
RUN git -C /home/opam/opam-repository pull origin master && opam update
RUN opam pin add no-camlp4 https://github.com/avsm/no-camlp4.git
COPY . /home/opam/src
RUN sudo chown -R opam /home/opam/src
RUN opam remote add mirage /home/opam/src
RUN opam depext -u mirage-core odig odoc
RUN opam install -yj3 mirage-core no-camlp4 odig odoc
RUN opam config exec -- odig odoc --docdir-href ../_doc
EXPOSE 8080
ENTRYPOINT opam config exec -- cohttp-server-lwt /home/opam/.opam/4.04.2/var/cache/odig/odoc
